version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web.dev
    volumes:
      # You will need this for the nodemon
      - ./:/usr/src/app/web
      - /usr/src/app/web/node_modules
    env_file: .env
    ports:
      - "$PORT:$PORT"
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker.dev
    volumes:
      # You will need this for the nodemon
      - ./:/usr/src/app/worker
      - /usr/src/app/worker/node_modules
    env_file: .env
  encryption:
    build:
      context: .
      dockerfile: Dockerfile.encryption.dev
    volumes:
      # You will need this for the nodemon
      - ./:/usr/src/app/encryption
      - /usr/src/app/encryption/node_modules
    env_file: .env